### ISSUE TITLE
Load not working

### ISSUE THREAD

**Issue by pgil5** [RHEAGROUP/EcoreNetto#2]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the EcoreNetto
- [x] I have searched [open](https://github.com/RHEAGROUP/EcoreNetto/issues) and [closed](https://github.com/RHEAGROUP/EcoreNetto/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The problem is that when I try to use the code of [ecorenetto.org](https://ecorenetto.org/gettingstarted.html):

```
public void Load()
{
     var path = "some-file-path.ecore";
     var uri = new Uri(path);
     var resourceSet = new ResourceSet();
     var resource = ResourceSet.CreateResource(uri);
     var root = resource.Load(null);
}
```

 I get the this error:

**System.ArgumentException: 'The resource http://www.eclipse.org/emf/2002/Ecore is invalid.'**

Is there a way to avoid it? I tried to search for code examples or documentation where I could see what arguments does `resource.load` read, but found nothing.

### Steps to Reproduce

Run the `Load` function above.

### System Configuration

- EcoreNetto: v1.0.3
- Environment (Operating system, version and so on): Microsoft Visual Studio 2019, Windows 10.
- .NET Framework version: .NET Core 3.1.13

**Comment by samatrhea** [comment]
would it be possible to share the ecore file? then we can try to reproduce the issue

**Comment by pgil5** [comment]
Ok, thank you.

Ensure to change the file extension manually because GitHub doesn't support _.ecore_ files.

[wizardEcore.txt](https://github.com/RHEAGROUP/EcoreNetto/files/6540059/wizardEcore.txt)

**Comment by samatrhea** [comment]
@pgil5 i am working on getting this fixed, there is a bug in the SW, your sample ecore model is helping with resolving the problem. Get back to as soon as i have the solution implemented. Not overly complicated, just some work.

**Comment by samatrhea** [comment]
@pgil5 should be working now, let me know whether you can manage to load your ecore file using version 1.1.0 which is now available on nuget.org
